### ISSUE TITLE
Voice from a song

### ISSUE THREAD

**Issue by karneaud** [Jam3/voice-activity-detection#3]
Can this utility detect voice in a song? actual singing?

**Comment by realdeemy** [comment]
It would not work well with music as the utility is only trying to differentiate silence vs voice from the mic input. 
Some beats or noises can be recognized as activity even though it's trying to check the length of the incoming sound bit.

**Comment by loretoparisi** [comment]
@namniak @karneaud   that's a good, point! By the way supposed I have an `<audio>` tag and I would like to run the VAD from that, what shall I have to use as `stream` parameters? thanks
